import { createServer } from 'node:http';
import { readFile, stat } from 'node:fs/promises';
import { extname, join, normalize } from 'node:path';
import { chromium } from 'playwright';
const DIST='/Users/andrewbogdanovyuohonov/Projects/andrii-card/dist/';
const MIME={'.html':'text/html;charset=utf-8','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp','.woff2':'font/woff2'};
const s=createServer(async(req,res)=>{try{let p=decodeURIComponent((req.url||'/').split('?')[0]);if(p.endsWith('/'))p+='index.html';const f=join(DIST,normalize(p));const i=await stat(f).catch(()=>null);const t=i?.isDirectory()?join(f,'index.html'):f;res.writeHead(200,{'Content-Type':MIME[extname(t)]||'application/octet-stream'}).end(await readFile(t));}catch{res.writeHead(404).end('nf');}});
await new Promise(r=>s.listen(4402,r));
const b=await chromium.launch();
const ctx=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true});
const p=await ctx.newPage();
await p.goto('http://localhost:4402/',{waitUntil:'load'});
await p.evaluate(()=>document.fonts.ready);
await p.waitForTimeout(1200);
console.log('вверху страницы, кнопка видима:', await p.locator('[data-to-top]').evaluate(el=>el.hasAttribute('data-visible')));
await p.evaluate(()=>window.scrollTo(0,document.body.scrollHeight));
await p.waitForTimeout(900);
console.log('внизу страницы, кнопка видима:', await p.locator('[data-to-top]').evaluate(el=>el.hasAttribute('data-visible')));
await p.screenshot({path:'/Users/andrewbogdanovyuohonov/Projects/andrii-card/audit/to-top.png'});
await p.locator('[data-to-top]').click();
await p.waitForTimeout(1400);
console.log('после клика scrollY =', await p.evaluate(()=>Math.round(window.scrollY)));
await b.close(); s.close();
